# Generated by Django 5.0.2 on 2024-07-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_table_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
