# Generated by Django 5.0.2 on 2024-07-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(to='core.table'),
        ),
    ]
